exclude: |
  (?x)^(
    (\.venv|venv)/|
    migrations/|
    alembic/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 9.0.1
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: ["-q", "-r", "app", "-x", ".venv,migrations,alembic,tests"]
        pass_filenames: false
