apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: classapp-web
  namespace: default
  labels:
    app.kubernetes.io/name: classapp-web
    app.kubernetes.io/part-of: classapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: classapp-web
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
