apiVersion: v1
kind: Service
metadata:
  name: classapp-db-master
  namespace: default
  labels:
    app.kubernetes.io/name: classapp-db-master
    app.kubernetes.io/part-of: classapp
spec:
  type: ClusterIP
  selector:
    patroni-role: master
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: classapp-db-replica
  namespace: default
  labels:
    app.kubernetes.io/name: classapp-db-replica
    app.kubernetes.io/part-of: classapp
spec:
  type: ClusterIP
  selector:
    patroni-role: replica
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
