---
- name: Prepare hosts and install K3s
  hosts: k3s_cluster
  become: true
  roles:
    - common
    - k3s

- name: Bootstrap secrets and install Kubernetes monitoring stack
  hosts: k3s_master[0]
  become: true
  roles:
    - bootstrap_secrets
    - monitoring
