name: Build and Push to YCR

on:
  push:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: ycr-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: classapp

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Официальный нативный способ авторизации от Yandex Cloud в GitHub Actions
      - name: Yandex Cloud Authorize
        uses: yandex-cloud/yc-github-actions/authorize@v2
        with:
          key-json: ${{ secrets.YC_SA_KEY_JSON }}

      # Используем официальный login-action от Docker, который автоматически подхватит токен из шага выше
      - name: Login to Yandex Container Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: iam
          password: ${{ env.YC_IAM_TOKEN }} # Переменная автоматически инжектируется плагином Яндекса

      - name: Build and Push to YCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            cr.yandex/${{ secrets.YCR_REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            cr.yandex/${{ secrets.YCR_REGISTRY_ID }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
